repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0 # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
      - id: check-json
      - id: check-merge-conflict
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier
  - repo: git://github.com/elidupuis/mirrors-sass-lint
    rev: ""
    hooks:
      - id: sass-lint
  - repo: git://github.com/awebdeveloper/pre-commit-tslint/
    rev: v0.0.2
    hooks:
      - id: tslint
        additional_dependencies: ["tslint@5.0.0"]
